# Generated by Django 4.2.13 on 2024-05-17 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='position',
            field=models.CharField(choices=[('Point Guard', 'PG'), ('Shooting Guard', 'SG'), ('Small Froward', 'SF'), ('Power Forward', 'PF'), ('Center', 'C')], max_length=100),
        ),
    ]
